blueprint:
  name: Hue Switch and Shelly - 221
  description: |
    Control Lights and Reles by Philips Hue Dimmer Switch V2 and Shelly.
    Blueprint 1.05
    - using Script ; call script.switch_and_light
  source_url: https://github.com/msigut/ha-blueprint/blob/main/bp.hue.shelly.yaml
  domain: automation
  author: Martin Sigut

  input:
    # Hue Dimmer Switch
    my_remote:
      name: Dimmer Switch
      description: Philips Hue Dimmer Switch V2
      default: ""
      selector:
        device:
          integration: zha
          entity:
            domain: sensor
            device_class: battery
    # tlacitka
    my_button:
      name: Shelly switch
      description: Shelly switch
      default: ""
      selector:
        device:
          manufacturer: Shelly
          multiple: false
    # prepinace
    my_rele:
      name: Switch
      description: Switches to control
      default: []
      selector:
        entity:
          domain: switch
          multiple: true
    # svetla
    my_light:
      name: Lights
      description: Lights to control
      default: []
      selector:
        entity:
          domain: light
          multiple: true
    # Helper - DropDown pro vyber scen
    my_scene_selector:
      name: Scene selector
      description: Helper - Dropdown as Scene selector
      default: ""
      selector:
        entity:
          filter:
            domain:
              - input_select
    # nastaveni: High Brightness
    brightness_default:
      name: Default Brightness in %
      description: Default Brightness for Power Enable (long-press - Hue On)
      default: 80
      selector:
        number:
          min: 10
          max: 100
          mode: slider
          step: 10
    # nastaveni: krok jasu
    brightness_step:
      name: Brightness Step in %
      description: Brightness Step in %  (click / hold - Hue Up / Down)
      default: 10
      selector:
        number:
          min: 10
          max: 50
          mode: slider
          step: 5
    # nastaveni: cas zmeny
    transition:
      name: Transition in sec
      description: Transition time (used in all operations)
      default: 1.0
      selector:
        number:
          min: 0.1
          max: 2.0
          mode: slider
          step: 0.1

mode: single

variables:
  # main
  my_rele: !input my_rele
  my_light: !input my_light
  my_scene_selector: !input my_scene_selector
  # brightness and transition
  brightness_default: !input brightness_default
  brightness_step: !input brightness_step
  brightness_step_fast: "{{ brightness_step * 2 }}"
  transition: !input transition
  # scenes
  scene_group: "{{ my_scene_selector.split('_')[2] | default('') }}"
  scene_off: "scene.{{scene_group}}_off"
  # lights
  light_on: "{{ states.light | selectattr('entity_id', 'in', my_light) | selectattr('state','eq','on') | map(attribute='entity_id') | list }}"
  light_on_count: "{{ light_on | count }}"

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input my_remote
      cluster_id: 64512
  - platform: event
    event_type: shelly.click
    event_data:
      device_id: !input my_button

action:
  - variables:
      command: "{{ trigger.event.data.command | default('') }}"
      click: "{{ trigger.event.data.click_type | default('') }}"

  - choose:
      # Enable / disable
      - conditions: "{{ command == 'on_short_release' or click == 'single_push' }}"
        sequence:
          - service: script.switch_and_light
            data:
              switches: "{{my_rele}}"
              lights: "{{my_light}}"
          - service: logbook.log
            data:
              name: HueShelly
              message: "ON / OFF"
      # Power enable
      - conditions: "{{ command == 'on_long_release' or click == 'long_push' }}"
        sequence:
          - service: script.switch_and_light
            data:
              switches: "{{my_rele}}"
              lights: "{{my_light}}"
              brightness: "{{brightness_default}}"
          - service: logbook.log
            data:
              name: HueShelly
              message: "ON-DIRECT | Brightness [{{brightness_default}}]"
      # Brightness up
      - conditions: "{{ command == 'up_press' and light_on_count > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{my_light}}"
            data:
              brightness_step_pct: "+{{brightness_step}}"
              transition: "{{transition}}"
          - service: logbook.log
            data:
              name: HueShelly
              message: "Hue BRIGHT UP | Step: [+{{brightness_step}}%] | Transition: [{{transition}}]"
      # Brightness down
      - conditions: "{{ command == 'down_press' and light_on_count > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{my_light}}"
            data:
              brightness_step_pct: "-{{brightness_step}}"
              transition: "{{transition}}"
          - service: logbook.log
            data:
              name: HueShelly
              message: "Hue BRIGHT DOWN | Step: [-{{brightness_step}}%] | Transition: [{{transition}}]"
      # Fast Brightness up
      - conditions: "{{ command == 'up_hold' and light_on_count > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{my_light}}"
            data:
              brightness_step_pct: "+{{brightness_step_fast}}"
              transition: "{{transition}}"
          - service: logbook.log
            data:
              name: HueShelly
              message: "Hue BRIGHT UP FAST | Step: [+{{brightness_step_fast}}%] | Transition: [{{transition}}]"
      # Fast Brightness down
      - conditions: "{{ command == 'down_hold' and light_on_count > 0 }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: "{{my_light}}"
            data:
              brightness_step_pct: "-{{brightness_step_fast}}"
              transition: "{{transition}}"
          - service: logbook.log
            data:
              name: HueShelly
              message: "Hue BRIGHT DOWN FAST | Step: [-{{brightness_step_fast}}%] | Transition: [{{transition}}]"
      # Scene next
      - conditions: "{{ command == 'off_press' }}"
        sequence:
          - service: input_select.select_next
            target:
              entity_id: "{{ my_scene_selector }}"
            data:
              cycle: true
          - service: logbook.log
            data:
              name: HueShelly
              message: "Hue SCENE NEXT"
      # Scene off
      - conditions: "{{ command == 'off_double_press' and light_on_count > 0 }}"
        sequence:
          - service: scene.turn_on
            data:
              entity_id: "{{scene_off}}"
          - service: logbook.log
            data:
              name: HueShelly
              message: "Hue SCENE OFF | Scene: [{{scene_off}}]"
