blueprint:
  name: Scene Watcher
  description: Sleduje změny scén. Blueprint 1.0 (build 4)
  domain: automation
  author: Martin Sigut
variables:
  scene_prefix: "input_select.scenes_"
trigger:
  - platform: event
    event_type: state_changed
condition:
  - condition: template
    value_template: "{{ trigger.event.data.entity_id.startswith(scene_prefix) }}"
action:
  - variables:
      scene_sel: "{{trigger.event.data.entity_id | replace(scene_prefix,'')}}"
      scene_cur: "{{trigger.event.data.new_state.state.lower() }}"
      scene_id: scene.{{scene_sel}}_{{scene_cur}}
  - service: scene.turn_on
    data_template:
      entity_id: "{{scene_id}}"
  - service: logbook.log
    data:
      name: SceneWatcher
      message: "Scene changed: {{scene_id}} | id: [{{trigger.event.data.entity_id}}]"
