blueprint:
  name: Scene Watcher
  description: Sleduje změny scén. Blueprint 1.0 (build 5)
  source_url: https://github.com/msigut/ha-blueprint/blob/main/bp.scene.watcher.yaml
  domain: automation
  author: Martin Sigut
variables:
  scene_prefix: "input_select.scenes_"
trigger:
  - platform: event
    event_type: state_changed
condition:
  - condition: template
    value_template: "{{ trigger.event.data.entity_id.startswith(scene_prefix) }}"
action:
  - variables:
      scene_group: "{{ trigger.event.data.entity_id.split('_')[2] | default('') }}"
      scene_cur: "{{ trigger.event.data.new_state.state.lower() | default('') }}"
      scene_id: "scene.{{scene_group}}_{{scene_cur}}"
  - service: scene.turn_on
    data_template:
      entity_id: "{{scene_id}}"
  - service: logbook.log
    data:
      name: SceneWatcher
      message: "Scene changed: {{scene_id}} | id: [{{trigger.event.data.entity_id}}]"
